CREATE TABLE PIZZA_ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50),
    PIZZA_TYPE VARCHAR2(50),
    ORDER_DATE DATE
);


DECLARE
    V_ORDER_ID    PIZZA_ORDERS.ORDER_ID%TYPE;
    V_CUSTOMER    PIZZA_ORDERS.CUSTOMER_NAME%TYPE;
    V_PIZZA       PIZZA_ORDERS.PIZZA_TYPE%TYPE;
BEGIN
    SELECT ORDER_ID, CUSTOMER_NAME, PIZZA_TYPE
    INTO V_ORDER_ID, V_CUSTOMER, V_PIZZA
    FROM PIZZA_ORDERS
    WHERE ORDER_ID = :ORDER_ID;

    DBMS_OUTPUT.PUT_LINE(V_ORDER_ID || '- 주문한 고객: ' || V_CUSTOMER || ', 피자 종류: ' || V_PIZZA);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('주문이 없습니다');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('데이터가 너무 많음');
END;

INSERT INTO PIZZA_ORDERS VALUES (101, 'Alice', 'Pepperoni', SYSDATE);