/*
CREATE OR REPLACE PROCEDURE STD_INFO
(
    V_STUDNO STUDENT.STUDNO%TYPE
)
IS
	O_NAME STUDENT.NAME%TYPE;
    O_GRADE STUDENT.GRADE%TYPE; 
BEGIN
	SELECT NAME, GRADE INTO O_NAME, O_GRADE
    FROM STUDENT
    WHERE STUDNO = V_STUDNO;

	 DBMS_OUTPUT.PUT_LINE('학생 이름: ' || O_NAME || '학년: ' || O_GRADE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('해당 학번의 학생이 없습니다.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('예상치 못한 오류 발생');
END STD_INFO;
*/

CALL STD_INFO(9715);
CALL STD_INFO(9613);